name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      run: |
        wget -qO- https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Set up virtual environment
      run: |
        uv venv
        echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync

    - name: Run format
      run: |
        uv run black crisp-py/crisp/ crisp-py/tests/
        uv run isort crisp-py/crisp/ crisp-py/tests/

    - name: Run check
      run: uv run mypy crisp-py/crisp/

    - name: Run test
      run: |
        cd ..
        uv run pytest crisp-py/tests/ -v